# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wlgls
brief-intro: Unremitting efforts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wlgls.github.io" # the base hostname & protocol for your site

permalink: /posts/:title

# other links
twitter_username: 
facebook_username: 
github_username:  Wlgls
email: Wlgls@gmail.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: 不懈进取！永无止境！

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
